module.exports = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    { 'Links Adicionales': [{ type: 'link', href: 'https://public.3.basecamp.com/p/gn3Tw4xcJxe2aNBjwM2WUn87', label: 'Documentación API' }] },
  ],
};
